%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ICSI471/571 Introduction to Computer Vision Fall 2025
% Copyright: Xin Li@2024-2026
% Computer Assignment 3: Image Enhancement
% Due Date: Sep. 30, 2025
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% General instructions: 
% 1. Wherever you see a pair of <...>, you need to replace <>
% by the MATLAB code you come up with
% 2. Wherever you see a pair of [...], you need to write a new MATLAB
% function with the specified syntax
% 3. Wherever you see a pair of {...}, you need to write your answers as
% MATLAB annotations, i.e., starting with %

% The objective of this assignment is to play with various image
% filtering and transform related MATLAB functions and feel about the difference
% between linear and nonlinear filters.
% MATLAB functions: hit, imhist, histeq, adapthisteq, localcontrast, imsharpen 

% Part 1: Histogram-based image enhancement experiments (6 points)

% 1. calculate the histogram of a given image (2 points)
x=double(imread('cube.tif'));
%[write a matlab function names my_hist.m to calculate the histogram
%for a given image]
h_x=my_hist(x,256);
% now call the hist function provided by matlab
h_ref=hist(x(:),1:256);
% compare the two results
<display the two histograms side by side> 
{do they look similar?}

% 2. enhancement of a microarray image (2 points)
x=double(imread('microarray.png'));
% >help histeq 
x_enh1=<enhance this image by histogram equalization>;
imshow(x_enh1/255,[]);
% >help adapthisteq 
x_enh2=<enhance this image by adaptive histogram equalization>;
imshow(x_enh2/255,[]);
 {what is the difference between two enhanced images?}
 
% 3. histogram matching (2 points)
% Learn how to use histeq function to process an input image A such that
% the histogram of the output matches that of a target image B
A=double(imread('cube.tif'));
B=double(imread('cameraman.tif'));
% create a new image (A_modified) such its histogram is similar to that
% of image B (they won't be identical due to low dynamic range)
A_modified=<your code enters here>;
imshow(A_modified/255,[]);
hA=hist(A_modified(:),1:256);hB=hist(B(:),1:256);
i=1:256;plot(i,hA,i,hB);

% Part 2 (Bonus). where is the teapot? (1 point)
% try to apply what you have learned to enhance a poor-quality
% image due to low-resolution and low-illumination (teapot.png). 
% Alternatively, you can work with the moon shot generated by CA1.
% The objective is to enhance the visual quality of moon image by a
% combination of the tools you have learned so far.
% Hint: you might want to combine image enhancement with image interpolation.
A=double(imread('teapot.png'));
<your codes go here and name the enhanced image B>
% side-by-side comparison
subplot(1,2,1);imshow(A/255,[]);
subplot(1,2,2);imshow(B/255,[]);
